### ISSUE TITLE
plz index this PMC paper

### ISSUE THREAD

**Issue by egonw** [wikipathways/pfocr-database#8]
PMID: 34096267 PMCID: [PMC8453666](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc8453666/) DOI: [10.1021/acs.est.1c01132](https://doi.org/10.1021/acs.est.1c01132)

ToC graphics (pathway in article is richer in content):

![image](https://github.com/wikipathways/pfocr-database/assets/26721/2bfc9a98-50e9-45b9-a8ab-22e7cfebee1d)

**Comment by AlexanderPico** [comment]
Here are the instructions for manually submitting figures for the PFOCR pipeline. Obviously still in development. A tool that takes a PMID and figure number would be cool, but doesn't exist yet.

https://github.com/wikipathways/pfocr-pmcfigurebot/blob/main/figures/README.md

**Comment by AlexanderPico** [comment]
And the tool to request figures does now exist :) 
https://github.com/wikipathways/pfocr-pmcfigurebot/issues/new?assignees=&labels=fetch&projects=&template=fetch_this_figure_issue.yml&title=%5BFetch%5D+Please+include+this+pathway+figure
